-- Seed events
INSERT INTO events (name, date, location, blurb, partiful_url, cover_image, cover_video, produced_by_slowhrs, is_public)
VALUES
  ('VOGUE SAFARI: CONTENT PRE GAME',
   '2025-05-08 19:00:00-07:00',
   'Los Angeles',
   'luxury safari editorial. photo shoot + content pre game for models, creatives, and good energy. come camera ready.',
   'https://partiful.com/e/1G8p2pfAqQsOiV4y3aHO',
   NULL,
   '/assets/events/block_party.mp4',
   true,
   true),

  ('Block Party',
   '2025-08-12 21:00:00-07:00',
   'Mid-City, Los Angeles',
   'crew run. hosts in the room. doors at 9.',
   NULL,
   NULL,
   '/assets/events/block_party.mp4',
   true,
   true),

  ('Destroy Lonely · WYA Trap Rave',
   '2025-03-14 22:30:00-07:00',
   'Los Angeles',
   'we shot the room. destroy lonely on stage. crew on the floor.',
   NULL,
   NULL,
   '/assets/events/destroy_lonely.mp4',
   false,
   true),

  ('NYE Recap',
   '2024-12-31 22:00:00-08:00',
   'Los Angeles',
   'we made it to the next year. here''s how.',
   NULL,
   NULL,
   '/assets/events/newyears.mp4',
   true,
   true),

  ('Fast Life Campaign',
   '2024-11-20 14:00:00-08:00',
   'Hollywood, Los Angeles',
   'the clothing reel. on hollywood. fall drop.',
   NULL,
   NULL,
   '/assets/drops/fast_life_reel.mp4',
   true,
   true),

  ('Runway · Spring Show',
   '2025-04-25 20:00:00-07:00',
   'Los Angeles',
   'the runway. one night only. members in the front row.',
   NULL,
   NULL,
   '/assets/videos/hero-recap.mp4',
   true,
   true);
